# Generated by Django 3.0.2 on 2020-01-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
